// AUTO-GENERATED by Craft Creator
onEvent('recipes', event => {
    // REMOVED-RECIPES-START
    // ADDED-RECIPES-START
	// crushing-recipes
	event.custom({"type":"create:crushing","ingredients":[{"item":"infinity:orichalcum"}],"results":[{"item":"infinity:orichalcum_dust","count":3}],"processingTime":0})
})
