// AUTO-GENERATED by Craft Creator
onEvent('recipes', event => {
    // REMOVED-RECIPES-START
    // ADDED-RECIPES-START
	// pulverizer-recipes
	event.custom({"type":"thermal:pulverizer","energy":100.0,"experience":0.4,"ingredient":{"item":"infinity:orichalcum"},"result":[{"item":"infinity:orichalcum_dust","count":1},{"item":"infinity:orichalcum_dust","count":1,"chance":0.25}]})
})
